// Code generated by protoc-gen-go. DO NOT EDIT.
// source: traffic.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	traffic.proto

It has these top-level messages:
	ReqPost
	Msg
	Entries
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// command
type ReqPost struct {
	PostId   []byte `protobuf:"bytes,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Topic    []byte `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Entry    []byte `protobuf:"bytes,3,opt,name=Entry,proto3" json:"Entry,omitempty"`
	Schedule []byte `protobuf:"bytes,4,opt,name=Schedule,proto3" json:"Schedule,omitempty"`
	Tags     []byte `protobuf:"bytes,5,opt,name=Tags,proto3" json:"Tags,omitempty"`
}

func (m *ReqPost) Reset()                    { *m = ReqPost{} }
func (m *ReqPost) String() string            { return proto.CompactTextString(m) }
func (*ReqPost) ProtoMessage()               {}
func (*ReqPost) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReqPost) GetPostId() []byte {
	if m != nil {
		return m.PostId
	}
	return nil
}

func (m *ReqPost) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *ReqPost) GetEntry() []byte {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *ReqPost) GetSchedule() []byte {
	if m != nil {
		return m.Schedule
	}
	return nil
}

func (m *ReqPost) GetTags() []byte {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Msg struct {
	Id       []byte   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Time     int64    `protobuf:"varint,2,opt,name=Time" json:"Time,omitempty"`
	Released bool     `protobuf:"varint,3,opt,name=Released" json:"Released,omitempty"`
	Post     *ReqPost `protobuf:"bytes,4,opt,name=Post" json:"Post,omitempty"`
	Entry    *Entries `protobuf:"bytes,5,opt,name=Entry" json:"Entry,omitempty"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Msg) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Msg) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Msg) GetReleased() bool {
	if m != nil {
		return m.Released
	}
	return false
}

func (m *Msg) GetPost() *ReqPost {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *Msg) GetEntry() *Entries {
	if m != nil {
		return m.Entry
	}
	return nil
}

type Entries struct {
	Id    []byte `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Topic []byte `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	File  []byte `protobuf:"bytes,3,opt,name=File,proto3" json:"File,omitempty"`
	Key   int64  `protobuf:"varint,4,opt,name=Key" json:"Key,omitempty"`
}

func (m *Entries) Reset()                    { *m = Entries{} }
func (m *Entries) String() string            { return proto.CompactTextString(m) }
func (*Entries) ProtoMessage()               {}
func (*Entries) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Entries) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Entries) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *Entries) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Entries) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqPost)(nil), "pb.ReqPost")
	proto.RegisterType((*Msg)(nil), "pb.Msg")
	proto.RegisterType((*Entries)(nil), "pb.Entries")
}

func init() { proto.RegisterFile("traffic.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x69, 0x93, 0xee, 0x2e, 0xb3, 0x2a, 0x32, 0x88, 0x04, 0x2f, 0x6a, 0x4f, 0x9e, 0x7a,
	0xd0, 0x67, 0x50, 0x58, 0x44, 0x90, 0xb8, 0x3e, 0x40, 0xdb, 0xcc, 0xae, 0x81, 0x6a, 0x62, 0x13,
	0x0f, 0x7b, 0xf0, 0x01, 0x7c, 0x6b, 0xc9, 0x6c, 0xac, 0x07, 0x3d, 0xf5, 0xff, 0xbf, 0x19, 0xfa,
	0xff, 0x19, 0x38, 0x8c, 0x63, 0xbb, 0xd9, 0xd8, 0xbe, 0xf1, 0xa3, 0x8b, 0x0e, 0x4b, 0xdf, 0xd5,
	0x9f, 0x30, 0xd7, 0xf4, 0xfe, 0xe8, 0x42, 0xc4, 0x53, 0x98, 0xa5, 0xef, 0xca, 0xa8, 0xe2, 0xa2,
	0xb8, 0x3a, 0xd0, 0xd9, 0xe1, 0x09, 0x54, 0x6b, 0xe7, 0x6d, 0xaf, 0x4a, 0xc6, 0x7b, 0x93, 0xe8,
	0xed, 0x5b, 0x1c, 0x77, 0x4a, 0xec, 0x29, 0x1b, 0x3c, 0x83, 0xc5, 0x53, 0xff, 0x42, 0xe6, 0x63,
	0x20, 0x25, 0x79, 0x30, 0x79, 0x44, 0x90, 0xeb, 0x76, 0x1b, 0x54, 0xc5, 0x9c, 0x75, 0xfd, 0x55,
	0x80, 0x78, 0x08, 0x5b, 0x3c, 0x82, 0x72, 0xca, 0x2d, 0x57, 0x86, 0x77, 0xed, 0x2b, 0x71, 0xa4,
	0xd0, 0xac, 0xd3, 0xbf, 0x35, 0x0d, 0xd4, 0x06, 0x32, 0x1c, 0xba, 0xd0, 0x93, 0xc7, 0x73, 0x90,
	0xa9, 0x2d, 0x67, 0x2e, 0xaf, 0x97, 0x8d, 0xef, 0x9a, 0xfc, 0x2c, 0xcd, 0x03, 0xbc, 0xfc, 0xa9,
	0x5b, 0xfd, 0x6e, 0x24, 0x60, 0x29, 0xe4, 0xee, 0xf5, 0x33, 0xcc, 0x33, 0xf9, 0x53, 0xe7, 0xff,
	0x13, 0x20, 0xc8, 0x3b, 0x3b, 0x50, 0xbe, 0x00, 0x6b, 0x3c, 0x06, 0x71, 0x4f, 0x3b, 0xee, 0x21,
	0x74, 0x92, 0xdd, 0x8c, 0x8f, 0x7d, 0xf3, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xf5, 0x37, 0x62,
	0x7d, 0x01, 0x00, 0x00,
}
